### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lmeszaros** [jdtuck/fdasrsf_python#1]
Installation failed, see the error message below:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

python setup.py install
running install
running build
running build_py
running build_ext
skipping 'src\optimum_reparamN.c' Cython extension (up-to-date)
building 'optimum_reparamN' extension
**error: Unable to find vcvarsall.bat**

**Comment by jdtuck** [comment]
This needs to be compiled from c and can have issues on windows. I don't use windows, but the link below talks about your error

https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat

This has to do with your python install and access to a compiler

**Comment by lmeszaros** [comment]
Thanks a lot for your quick reply!

Best,

Lorinc Meszaros
+31617605307
