### ISSUE TITLE
Generated C files should not be in the repo

### ISSUE THREAD

**Issue by vnmabus** [jdtuck/fdasrsf_python#12]
Is there any reason for C files that are generated by Cython to be part of the repository? It adds noise to the git staging process, as the generated files on my computer do not match exactly the files in Git.

**Comment by jdtuck** [comment]
Currently no, but to explain back when we are running this on the hpc at snl, we needed them. I will remove them.

**Comment by jdtuck** [comment]
Also not a problem when I was the only one on the project ;-). Appreciate the help.
