### ISSUE TITLE
Question on re-parametrization

### ISSUE THREAD

**Issue by ethancohen123** [jdtuck/fdasrsf_python#15]
Hi, 
I have a question concerning the invariance with respect to re-parametrization. 
Is that mean that I could start the shapes wherever I want and that is not a problem ? Or I should always (close or open curves) start from a defined origin point ? In my case I know that all of my curves have a point in correspondence and I can have the label for this point . Is it useful to start all curves with this point or the re-parametrisation invariance solve this issue ? 
Thank you

**Comment by jdtuck** [comment]
So open curves if you have the information it is good to have it start from the same point. For closed curves it searches for the optimum start point for alignment. Re-parametrization is invariance to sampling variability along the curve.
