### ISSUE TITLE
References for the Elastic distance

### ISSUE THREAD

**Issue by kiranvad** [jdtuck/fdasrsf_python#18]
Hi,
Thanks a lot for open sourcing this codebase. I find it very useful.
I was trying to understand the elastic distance in https://github.com/jdtuck/fdasrsf_python/blob/f59bd74b570662c17a1a042556d4887e6a75fa3e/fdasrsf/umap_metric.py#L292 and was wondering if you've any paper/book that I can refer to.
From the implementation, it appears to me that it's different than the simple SRSF with the L2 metric distance one would compute (is it the amplitude distance?).
Any help would be greatly appreciated.

TIA
Kiran Vaddi

**Comment by jdtuck** [comment]
It’s not any different other than it’s set up to be used directly with the Python package ‘umap-learn’. It is the Fischer Rai distance but assumes input is two SRSFs. Just as all computation it uses Dynamic Programming to find the optimal alignment. If you aren’t using UMAP I would use ‘elastic_distance’
