### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by ekaterinailin** [jdtuck/fdasrsf_python#3]
Hello Derek,

first of all - this is a great package. I am currently playing around with it. 

**Some notes that lead to my suggestion:**

1. I had the same issue as in #2, which was solved after including your latest commits. I was wondering at some point if this had something to do with my numpy version, but it was fine (numpy=1.16.3). I am working on Ubuntu 18.04.

2. Packages that I had to install manually after `python setup.py install` were `joblib` and `patsy`.

3. Some matplotlib functionalities that you are using are deprecated in matplotlib 3.0. as it seems. I may be fixing some of them on the go, so if you are interested in that let me know.

**Suggestion: A requirements.txt file that states packages and their versions explicitly may help further users.**

Kind regards and thank you for the nice work!
Ekaterina

**Comment by jdtuck** [comment]
Thanks, I will work on this. I have been slammed lately so any fixes you have for the new matplotlib and any others would be greatly appreciated.

**Comment by jdtuck** [comment]
I should have a requirements file put up tonight.

**Comment by jdtuck** [comment]
Done
