### ISSUE TITLE
Remove `GPy` dependency

### ISSUE THREAD

**Issue by eliegoudout** [jdtuck/fdasrsf_python#32]
Hello,

Is it considered to try and remove the `GPy` dependency in a somewhat near future? It seems to be a not-so-well-maintained package, that cause installation issues for multiple Python versions, and definitely causes problem for python3.11. This is why more and more projects are dropping this dependency when possible.

Thanks for you time and your package :)
Cheers!

**Comment by jdtuck** [comment]
It is considered, need to find a suitable GP replacement

**Comment by jdtuck** [comment]
Though I have yet to find a good GP package that is complete and not part of something else's heavy.
