### ISSUE TITLE
Question: Why is this repo using the tarballs from https://anaconda.org/scientific-python-nightly-wheels/openblas-lib?

### ISSUE THREAD

**Issue by mattip** [jdtuck/fdasrsf_python#36]
I am [refactoring the openblas-libs build](https://github.com/MacPython/openblas-libs/pull/128) to change the name of the shared object in the tarballs at https://anaconda.org/scientific-python-nightly-wheels/openblas-lib, and this repo turned up in a [code search](https://github.com/search?q=anaconda.org%2Fscientific-python-nightly-wheels%2Fopenblas-libs&type=code) to see who else is using it. This repo is downloading it when building wheels via the `openblas_support.py` script. But my search foo is not good enough to see where in the code openblas is actually used, and what will break when the new tarballs go live. Could you help me out?

**Comment by vnmabus** [comment]
Is this maybe related to #37?

**Comment by mattip** [comment]
Maybe? It seems there is a package called crbfgs that is failing to import. I see it in the cython sources https://github.com/jdtuck/fdasrsf_python/blob/33dab0a9d46ea5c82f77b9e38c69eccd9aad8cc5/src/crbfgs.pyx#L3

But I don't see that in your [requirements](https://github.com/jdtuck/fdasrsf_python/blob/master/requirements.txt) and cannot find a reference to it in PyPI.

**Comment by vnmabus** [comment]
I will mention @jdtuck, just in case he did not read this issue.

**Comment by jdtuck** [comment]
@mattip it will not break anything and thank you for checking. It is used in a local CI setup. Don't worry about breaking that. Also not related to #37
