### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by mwilson221** [jdtuck/fdasrsf_python#44]
I'm having some issues importing fdasrsf

I install from command line with 

git clone https://github.com/jdtuck/fdasrsf_python.git
pip install ./fdasrsf_python

Working from a jupyter notebook in the same folder as fdasrsf_python;

import fdasrsf gives me a "ModuleNotFoundError"

and

import sys
sys.path.append('C:\\Users\\micha\\Documents\\GitHub\\Machine-Learning\\fdasrsf_project\\fdasrsf_python')
import fdasrsf

gives me

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Cell In[2], line 3
      1 import sys
      2 sys.path.append('C:\\Users\\micha\\Documents\\GitHub\\Machine-Learning\\fdasrsf_project\\fdasrsf_python')
----> 3 import fdasrsf

File ~\Documents\GitHub\Machine-Learning\fdasrsf_project\fdasrsf_python\fdasrsf\__init__.py:122
    120 from .geometry import inv_exp_map, exp_map
    121 from .geodesic import geod_sphere, path_straightening
--> 122 from .umap_metric import efda_distance, efda_distance_curve
    123 from .rbfgs import rlbfgs

File ~\Documents\GitHub\Machine-Learning\fdasrsf_project\fdasrsf_python\fdasrsf\umap_metric.py:9
      1 """
      2 Distance metrics for functions and curves in R^n for use with UMAP
      3 (https://github.com/lmcinnes/umap)
   (...)
      6 
      7 """
----> 9 import numba
     10 from numba.core.typing import cffi_utils
     11 from _DP import ffi, lib

File ~\anaconda3\lib\site-packages\numba\__init__.py:43
     39 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     40                                    jit_module)
     42 # Re-export vectorize decorators and the thread layer querying function
---> 43 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     44                             get_num_threads, set_num_threads)
     46 # Re-export Numpy helpers
     47 from numba.np.numpy_support import carray, farray, from_dtype

File ~\anaconda3\lib\site-packages\numba\np\ufunc\__init__.py:3
      1 # -*- coding: utf-8 -*-
----> 3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
      4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One
      5 from numba.np.ufunc import _internal, array_exprs

File ~\anaconda3\lib\site-packages\numba\np\ufunc\decorators.py:3
      1 import inspect
----> 3 from numba.np.ufunc import _internal
      4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder
      6 from numba.core.registry import TargetRegistry

SystemError: initialization of _internal failed without raising an exception

Any idea what the issue is?

**Comment by jdtuck** [comment]
Are you trying to import it from the cloned directory?

**Comment by jdtuck** [comment]
Also adding the path will screw everything up. What OS, what python version and I can help you.
