### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ethancohen123** [jdtuck/fdasrsf_python#5]
Is it possible to use this package with google colab ? I get this error when I want to install it via pip :
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Thanks

**Comment by jdtuck** [comment]
So without more of a log (tried on google collab for a while to find), I cannot really diagnose. The one main problem here is that this package relies on a large c++ library that is compiled when installing via pip and my guess there are missing libraries/compilers on google collab when you try to install it.

**Comment by jdtuck** [comment]
As a note, I just got this to work

```
!pip install findblas
!pip install fdasrsf
```

will try to fix on pip
