### ISSUE TITLE
Convergence and results

### ISSUE THREAD

**Issue by ethancohen123** [jdtuck/fdasrsf_python#9]
Hi,
I am trying to use you package for doing some statistical shape analysis following your notebook. It works fine with your dataset with the bones , but with my data the mean do not converge ( I have tried to increase the maxIteration ) and the results are not good . Do you know what may cause that and how I can fixed it ?
Thank you

**Comment by jdtuck** [comment]
So this depends on what your data looks like which leads me to a few questions:

1. Are they open or closed curves?
2. How many samples per curve?
3. How are you calling the fdacurve?
4. Can you share a picture of your data after you load into fdacurve, using the `plot` method?

**Comment by ethancohen123** [comment]
1. There are closed curves
2. 150 samples ( I can modify that as I take the contour points from a binary mask )
3.  Like this : obj = fs.fdacurve(shapes,N=M,mode='C',scale=True)
4 .
![Uploading cc.PNG…]()

**Comment by ethancohen123** [comment]
![cc](https://user-images.githubusercontent.com/55588944/97092119-0f441880-1639-11eb-8337-e01607e6a4c1.PNG)
1.There are closed curves
2. 150 samples ( I can modify that as I take the contour points from a binary mask )
3. Like this : obj = fs.fdacurve(shapes,N=M,mode='C',scale=True)
4 . Attached

**Comment by jdtuck** [comment]
So can you plot a few of the curves, some don’t even look to be from the same shape, but there are so many overlapped. Also a first try, set the mode to ‘O’ and see if we get a solution.

**Comment by jdtuck** [comment]
Also can you show me what you mean by the ‘results are not good’

**Comment by jdtuck** [comment]
Also one more check, are you sure they are closed (i.e., the last point is the same as the first point). The reason I ask is that from the plot (could be plotting) it looks like some are not.

**Comment by ethancohen123** [comment]
Thanks , I checked and the curves are indeed not close; the first and last point are a little bit different
Here is the some curves (10 ) plotted 
![closed](https://user-images.githubusercontent.com/55588944/97104826-b8792600-16ae-11eb-9df9-e7a564ead5dd.PNG)
PS: The curves represent the contour points of embryos shape at same age and same phenotype
About the results , here is what I get with 66 curves 
- It reaches maxIter and the optimization for the mean do not converge ( I've tried for maxIter=50 and 100 but it is the same )
- The mean shape doesnt look like what we expect for the mean shape ; The middle of the shape is not supposed to be that thin looking at the original data 
- The PC1 looks a bit weird : I am not sure but it seems that it the results should be more 'aligned ' as with the bones dataset in the example notebook
Thank you for you time 
![opti](https://user-images.githubusercontent.com/55588944/97105439-95507580-16b2-11eb-9dac-f0c1a1568ea8.PNG)
![mean](https://user-images.githubusercontent.com/55588944/97105445-9c778380-16b2-11eb-8464-c6b2858f769c.PNG)
![pc](https://user-images.githubusercontent.com/55588944/97105448-a13c3780-16b2-11eb-9487-1f50b6e71b61.PNG)

**Comment by jdtuck** [comment]
Okay, please run it as open curves and let me know if you get a similar result.

**Comment by ethancohen123** [comment]
It is the results with open curves

**Comment by jdtuck** [comment]
Hmm, there is something weird in a few of your curves then. I would check for duplicate points, also you can use the `resamplecurve` function to resample them all to say 100 points and see if that changes anything. It is something in the data. Can you share it?

**Comment by ethancohen123** [comment]
Here is a zip file with the 66 shapes in txt files. There is 150 points per curve
[control_point.zip](https://github.com/jdtuck/fdasrsf_python/files/5435623/control_point.zip)

**Comment by jdtuck** [comment]
So there is a bug, I am fixing now. The curves are supposed to be centered, in my example they are so close to the same its not a big deal, yours are not on centered at the origin. Will let you know once I release a fix. Working on it now. Sorry about that and thank you for asking your question

**Comment by jdtuck** [comment]
Have pushed the fix to the repo, have not released to pip till I have done some more testing. I still don't get results on your data that make 100 sense. I have ran your curves on the original MATLAB code and get the same result on open curves. There is something in your data that I am trying to figure out.

**Comment by jdtuck** [comment]
So after looking closer at your data you had curves sampled clockwise and others counterclockwise and the code assumes they are all in one direction. I am making a fix to `fdacurve` to check for this.

**Comment by ethancohen123** [comment]
Thank you very much for your time 
For the last point isnt it something that the framework should do ? I mean in the SRVF framework the registration problem is taken care implicitly during the optimization for the mean . So if the curves are registered , rotation shouldnt be removed right ? Unless the sampling problem is different from a rotation problem

**Comment by jdtuck** [comment]
So the SRVF handles rotation, scale, and reparameterization of the shapes. Rotation is the actual rotation of the scale in \mathbb{R}^n, where you would apply a rotation matrix. What I am talking about is not that. You had shapes that started from one starting point and traversed in sampling to the end point. You had other shapes that started at the end point and sampled to the starting point. Part of the SRVF is taking a derivative and these derivatives have different signs. The code assumed all curves in the set where sampled from one direction, especially when you choose open curves. For closed curves it will align the seed point (starting), but still assumes you sampled in the same direction at least. It is an easy fix. Let me know how your results look on the latest commit.

**Comment by ethancohen123** [comment]
Okay thank you , it is much clearer
Can I use it with pip or should I clone the git repo

**Comment by jdtuck** [comment]
Currently, you need to clone the repo, I have not released to pip or bumped the version yet

**Comment by jdtuck** [comment]
I got good results (what I think) on your data for open curves when I tested last night

**Comment by ethancohen123** [comment]
I have tested it , it is much better thank you !

**Comment by ethancohen123** [comment]
Also , if I turned them into closed curves , the bug is also fixed ? Because , in a next step, I want to align them with respect to a starting point that I will define . 
The starting point is a label point that I have for each curves corresponding to a biological feature in the embryos

**Comment by jdtuck** [comment]
Good to hear, and yes it is fixed for both open and closed.

**Comment by jdtuck** [comment]
I will tag a release here shortly
